.TH KISMETDB_STATISTICS "1" "July 2019" "User Commands"
.SH NAME
kismetdb_statistics \- statistics about a kismetdb file 
.SH SYNOPSIS
.B kismetdb_statistics
[\fI\,OPTION\/\fR]
.SH OPTIONS
.TP
\fB\-i\fR, \fB\-\-in\fR [filename]
Input kismetdb file
.TP
\fB\-s\fR, \fB\-\-skip\-clean\fR
Don't clean (sql vacuum) input database
.TP
\fB\-j\fR, \fB\-\-json\fR
Dump stats as a JSON dictionary
.SH "SEE ALSO"
The full documentation for
.B Kismet
is maintained in a separate package kismet-docs.
More information here: https://www.kismetwireless.net/docs
